### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by larsgrefer**
see https://github.com/ocpsoft/rewrite/issues/304#issuecomment-1062101480

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hey @larsgrefer - Thanks for this! Looks good.

Could you give me an overview of what the maven-wrapper and corresponding scripts are used for? It looks like it's related to Continuous Integration, but I want to be sure I understand what's going on here. I saw you added it to the rewrite project as well.

**Comment by larsgrefer** [comment]
The Maven Wrapper is basically a small application that downloads Maven and then executes the build.

This has the advantage that one does not need to have Maven installed locally and that the build is always executed with the same version of Maven.

The shell scripts in the root directory (`mvnw` and `mvnw.cmd`) are meant as a direct replacement for the mvn command, so instead of `mvn clean` you'd run `./mvnw clean`.

More information about this can be found here: https://maven.apache.org/wrapper/

**Comment by larsgrefer** [comment]
@lincolnthree I've just updated all the maven plugin version properties to their latest versions, but I'm not sure which of these plugins are actually needed.

Findbugs for example is de-facto dead and only works for Java 8 or lower.

**Comment by lincolnthree** [comment]
Thank you! This is very helpful. I think this makes sense. Yeah, updating to the latest versions is fine. I think our other projects should slowly start to come up to speed anyway.

**Pull request merged**
